[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
gas_reports = ['*']
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 7777
via_ir = true
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
dynamic_test_linking = true
fs_permissions = [{ access = "read-write", path = "." }]

[profile.solx]
gas_limit = 100_000_000

[invariant]
seed = '0x42'
runs = 256
depth = 128
fail_on_revert = true
call_override = false
preserve_state = true   

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
sort_imports = true

[lint]
lint_on_build = false

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
sepolia = "${RPC_SEPOLIA}"

[soldeer]
# whether soldeer manages remappings
remappings_generated = false
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false
# whether to suffix the remapping with the version: `name-a.b.c`
remappings_version = false

[dependencies]
forge-std = "1.10.0"
kam = { version = "v1", git = "https://github.com/VerisLabs/KAM.git" }
minimal-smart-account = { version = "1.0", git = "https://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@github.com/turingcapitalgroup/minimal-smart-account.git" }
